name: artwork-sharing-platform-deployed
services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_HOST=1
      - PMA_HOST=103.126.161.22
      - PMA_PORT=3306
